---
- name: Create /var/docker/atlantis directory
  ansible.builtin.file:
    dest: /var/docker/atlantis
    state: directory
    mode: 0755

- name: Check if the Docker Compose file exists
  ansible.builtin.stat:
    path: /var/docker/atlantis/docker-compose.yml
  register: atlantis_docker_compose_file

- name: Stop the Atlantis Docker containers
  community.docker.docker_compose_v2:
    project_src: /var/docker/atlantis
    state: absent
  when: atlantis_docker_compose_file.stat.exists

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: /var/docker/atlantis/Dockerfile
    mode: 0640

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /var/docker/atlantis/docker-compose.yml
    mode: 0640

- name: Create Atlantis env variables file
  ansible.builtin.template:
    src: "{{ atlantis_env_file }}"
    dest: /var/docker/atlantis/.env
    mode: 0640

- name: Copy Atlantis config
  ansible.builtin.copy:
    src: "{{ atlantis_config_file }}"
    dest: /var/docker/atlantis/atlantis_config.yml
    mode: 0640

- name: Start the Atlantis Docker containers
  community.docker.docker_compose_v2:
    project_src: /var/docker/atlantis
    state: present
    pull: always
    build: always
    recreate: always
