---
- name: Create /var/docker/atlantis directory
  ansible.builtin.file:
    dest: /var/docker/atlantis
    state: directory
    mode: 0755

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: /var/docker/atlantis/Dockerfile
    mode: 0655

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /var/docker/atlantis/docker-compose.yaml
    mode: 0655

- name: Create Atlantis env variables file
  ansible.builtin.template:
    src: atlantis_env.j2
    dest: /var/docker/atlantis/.env
    mode: 0655

- name: Copy Atlantis config
  ansible.builtin.copy:
    src: "{{ atlantis_server_config_file }}"
    dest: /var/docker/atlantis/atlantis_config.yml
    mode: 0655

- name: Start the Atlantis Docker containers
  community.docker.docker_compose:
    project_src: /var/docker/atlantis
    state: present
    pull: yes
