version: "3.8"

services:
  atlantis:
    build:
      context: .
    ports:
      - 4141:4141
    volumes:
      - atlantis-data:/var/lib/atlantis
      - ./atlantis_config.yml:/etc/atlantis/atlantis_config.yml
    restart: unless-stopped
    env_file:
      - .env

volumes:
  atlantis-data:
    driver: local